name: Test windows build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [build_sdist]
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_TEST_SKIP: "*"